//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWork.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string zip { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
    
        public virtual users user { get; set; }
    }
}
